/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sianu.internal;

import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Rectangle;
import java.io.File;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sianu.popup.Anggota;

/**
 *
 * @author BadikIrwan
 */
public final class FormAnggota extends javax.swing.JInternalFrame {
    Blob blob;
    Anggota anggota = new Anggota(null, true, this);
    File file;
    ImageIcon gambar;
    public boolean databaru; 
    /**
     * Creates new form FormAnggota
     */
    public FormAnggota() {
        initComponents();
        jumlah();
        getData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnBaru = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(855, 474));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("DATA ANGGOTA / LIHAT DATA");

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnBaru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sianu/icons/add.png"))); // NOI18N
        btnBaru.setText("Baru");
        btnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruActionPerformed(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sianu/icons/refresh.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sianu/icons/exit.png"))); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBaru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKembali)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh)
                    .addComponent(btnKembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Jumlah Anggota Total :");

        txtJumlah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pencarian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sianu/icons/search.png"))); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCari)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCari, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(btnCari, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 586, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtJumlah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 342, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtJumlah))
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruActionPerformed
        // TODO add your handling code here:
        databaru =true;
        anggota.clear();
        autokode();
        anggota.show();
    }//GEN-LAST:event_btnBaruActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
         try {
            int row = tabel.getSelectedRow();
            String tabel_klik=(tabel.getModel().getValueAt(row, 0).toString());
            Connection con =(Connection)sianu.koneksi.Koneksi.getKoneksi();
            Statement st = con.createStatement();
            ResultSet sql = st.executeQuery("SELECT * FROM kader WHERE id='"+tabel_klik+"'");
            if(sql.next()){
                anggota.txtID.setText(sql.getString("ID"));
                anggota.txtNama.setText(sql.getString("nama"));
                anggota.txtTmpLahir.setText(sql.getString("tmp_lahir"));
                String tgl = sql.getString("tgl_lahir");
                DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                Date date = format.parse(tgl);
                anggota.txtTglLahir.setDate(date);
                anggota.txtProfesi.setText(sql.getString("profesi"));
                anggota.txtAlamat.setText(sql.getString("alamat"));
                anggota.txtNoTlp.setText(sql.getString("no_kontak"));
                anggota.txtEmail.setText(sql.getString("email"));
                anggota.txtKhidup.setText(sql.getString("k_hidup"));
                anggota.txtPendFormal.setText(sql.getString("pend_formal"));
                anggota.txtPendNonFormal.setText(sql.getString("pend_nonformal"));
                anggota.txtKorganisasi.setText(sql.getString("k_organisasi"));
                anggota.txtRkader.setText(sql.getString("riwayat_kaderisasi"));
                anggota.txtFb.setText(sql.getString("fb"));
                anggota.txtTwitter.setText(sql.getString("twitter"));
                anggota.txtInstagram.setText(sql.getString("instagram"));
                String foto = sql.getString("foto");
                anggota.nm.setText(foto);
                String path = "D:/APP/image/";
                ImageIcon image = new ImageIcon(path+foto);
                Rectangle rect = anggota.gambar.getBounds();
                Image scaledimage = image.getImage().getScaledInstance(rect.width,rect.height,Image.SCALE_DEFAULT);
                image = new ImageIcon(scaledimage);
                anggota.gambar.setIcon(image);
            } 
        } catch (SQLException | ParseException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        } 
        anggota.show();
    }//GEN-LAST:event_tabelMouseClicked

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
         DefaultTableModel tbm = new DefaultTableModel();
         tbm.addColumn("ID");
         tbm.addColumn("Nama");
         tbm.addColumn("PROFESI");
         tbm.addColumn("NO TELEPON");
         tbm.addColumn("ALAMAT");
        try {
            Connection con = sianu.koneksi.Koneksi.getKoneksi();
            String sql = "Select * from kader where id like '%" + txtCari.getText() + "%'" +
            "or nama like '%" + txtCari.getText() + "%'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if(rs.next()) {
            tbm.addRow(new Object[]{
             rs.getString("id"), rs.getString("nama"),rs.getString("profesi"), rs.getString("no_kontak"),rs.getString("alamat")});
               tabel.setModel(tbm);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Data tidak ada");
            }
        } catch(SQLException | HeadlessException e) {
            
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        getData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    public void autokode() {
        try {
            Connection con = sianu.koneksi.Koneksi.getKoneksi();
            Statement state = con.createStatement();
            String sql = "select max(ID) from kader";
            ResultSet rs = state.executeQuery(sql);
            while(rs.next()){
             int a = rs.getInt(1);
            anggota.txtID.setText("000"+Integer.toString(a+1));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    public void jumlah() {
        try {
           Connection con = sianu.koneksi.Koneksi.getKoneksi();
           Statement st =  con.createStatement();
           String sql = "select sum(kader) from kader"; 
        } catch(SQLException e) {
            
        }
    }
    
    public void aktif(boolean a) {
        anggota.txtID.setEditable(a);
        anggota.txtNama.setEditable(a);
        anggota.txtTmpLahir.setEditable(a);
        anggota.txtTglLahir.setEnabled(a);
        anggota.txtAlamat.setEditable(a);
        anggota.txtNoTlp.setEditable(a);
        anggota.txtKhidup.setEditable(a);
        anggota.txtProfesi.setEditable(a);
        anggota.txtPendFormal.setEditable(a);
        anggota.txtPendNonFormal.setEditable(a);
        anggota.txtRkader.setEditable(a);
        anggota.txtKorganisasi.setEditable(a);
        anggota.txtFb.setEditable(a);
        anggota.txtTwitter.setEditable(a);
        anggota.txtInstagram.setEditable(a);
        anggota.btnPilih.setEnabled(a);
        anggota.btnSimpan.setEnabled(a);
    }
    
    public void getData() {
        DefaultTableModel tbm = new DefaultTableModel();
        tbm.addColumn("ID");
        tbm.addColumn("NAMA");
        tbm.addColumn("PROFESI");
        tbm.addColumn("NO TELEPON");
        tbm.addColumn("ALAMAT");
        try {
            Connection con = (Connection)sianu.koneksi.Koneksi.getKoneksi();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from kader");
            while(rs.next()) {
                tbm.addRow(new Object[] {
                    rs.getString("id"), rs.getString("nama"),rs.getString("profesi"), rs.getString("no_kontak"),rs.getString("alamat")});
               tabel.setModel(tbm);
            }
        } catch(Exception e) {
            
        }
        int a = tbm.getRowCount();
        txtJumlah.setText(a+" Orang");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField txtCari;
    private javax.swing.JLabel txtJumlah;
    // End of variables declaration//GEN-END:variables
}
